/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'TaG' at '1/5/17 2:04 PM' with Gradle 2.14.1
 *
 * @author TaG, @date 1/5/17 2:04 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
